# 1. Imports.

In [44]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# 2. Data preparation
### 2.1. Load the data

In [45]:
data = pd.read_csv('census-income/adult.csv', na_values='?')
data.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,NaN,77053,HS-grad,9,Widowed,NaN,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,NaN,186061,Some-college,10,Widowed,NaN,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

### 2.2. Filtering unwanted features

In [46]:
data_filtered = data.drop(columns=["age", "fnlwgt", "education.num", "capital.gain", "capital.loss", "hours.per.week"]) # features only include discrete variables

data_filtered.head()

,workclass,education,marital.status,occupation,relationship,race,sex,native.country,income
0,NaN,HS-grad,Widowed,NaN,Not-in-family,White,Female,United-States,<=50K
1,Private,HS-grad,Widowed,Exec-managerial,Not-in-family,White,Female,United-States,<=50K
2,NaN,Some-college,Widowed,NaN,Unmarried,Black,Female,United-States,<=50K
3,Private,7th-8th,Divorced,Machine-op-inspct,Unmarried,White,Female,United-States,<=50K
4,Private,Some-college,Separated,Prof-specialty,Own-child,White,Female,United-States,<=50K

### 2.3. Handling missing values

In [47]:
for col in data_filtered.columns:
    data_filtered[col] = data_filtered[col].fillna("MISSING")

    data_filtered[col] = data_filtered[col].replace("?", "MISSING")

data_filtered.head()

,workclass,education,marital.status,occupation,relationship,race,sex,native.country,income
0,MISSING,HS-grad,Widowed,MISSING,Not-in-family,White,Female,United-States,<=50K
1,Private,HS-grad,Widowed,Exec-managerial,Not-in-family,White,Female,United-States,<=50K
2,MISSING,Some-college,Widowed,MISSING,Unmarried,Black,Female,United-States,<=50K
3,Private,7th-8th,Divorced,Machine-op-inspct,Unmarried,White,Female,United-States,<=50K
4,Private,Some-college,Separated,Prof-specialty,Own-child,White,Female,United-States,<=50K

### 2.4. Encoding the data

In [48]:
data_encoded = pd.DataFrame()
for col in data_filtered.columns:
    data_encoded[col] = data_filtered[col].astype('category')
    data_encoded[col] = data_encoded[col].cat.codes

data_encoded.head()

,workclass,education,marital.status,occupation,relationship,race,sex,native.country,income
0,2,11,6,6,1,4,0,39,0
1,4,11,6,3,1,4,0,39,0
2,2,15,6,6,4,2,0,39,0
3,4,5,0,7,4,4,0,39,0
4,4,15,5,10,3,4,0,39,0

### 2.5. Separating data to features and targets

In [49]:
x = data_encoded.drop(columns=["income"])
y = data_encoded["income"]

x.head()

,workclass,education,marital.status,occupation,relationship,race,sex,native.country
0,2,11,6,6,1,4,0,39
1,4,11,6,3,1,4,0,39
2,2,15,6,6,4,2,0,39
3,4,5,0,7,4,4,0,39
4,4,15,5,10,3,4,0,39

### 2.6. Splitting data

In [50]:
# first split 70% training and 30% temp
x_train, x_temp, y_train, y_temp = train_test_split(x,y, test_size = 0.29999, random_state = 42, stratify = y)

# then split temp into 15% validation and 15% test
x_val, x_test, y_val, y_test = train_test_split(x_temp, y_temp, test_size = 0.5, random_state = 42, stratify = y_temp)

In [51]:
print(f"Training set size: {x_train.shape[0]} samples")
print(f"Validation set size: {x_val.shape[0]} samples")
print(f"Test set size: {x_test.shape[0]} samples")

Training set size: 22793 samples
Validation set size: 4884 samples
Test set size: 4884 samples

# 3. Naive bayes implementation